dataset:
  data_dir: ???
  num_proc: 16

tokenizer:
  tokenizer_dir: ???

model:
  d_model: 512
  num_layers: 6
  num_heads: 8
  d_ff: 2048
  dropout_rate: 0.1
  max_length: 4096
  label_smoothing: 0.1
  ignore_token_id: -100

train:
  dataloader:
    train_batch_size: 8
    valid_batch_size: 8
    num_workers: 2
    pin_memory: true
  optimizer:
    lr: 7e-4
    weight_decay: 1e-2
    max_grad_norm: 1.0
  scheduler:
    warmup_steps: 4000
  epochs: 1
  grad_accum_steps: 8
  log_steps: 100
  out_dir: ???
  checkpoint_path:

evaluate:
  model_path: ???
  out_dir: ???
  beam_size: 3

hydra:
  # https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/
  output_subdir: null
  # https://hydra.cc/docs/configure_hydra/logging/
  job_logging:
    version: 1
    formatters:
      simple:
        format: "%(asctime)s - %(name)s - %(filename)s:%(lineno)d - %(levelname)s: %(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      handlers: [console]
    disable_existing_loggers: false
